'use client'
import { useState } from 'react'
import { Download, RefreshCw, BookOpen, Layers, HelpCircle, Trophy } from 'lucide-react'
import { NotesSection } from './NotesSection'
import { FlashcardsSection } from './FlashcardsSection'
import { MCQSection } from './MCQSection'
import { QuizSection } from './QuizSection'
import { InContentAd } from '@/components/ads/InContentAd'

const tabs = [
  { id: 'notes', label: 'Notes', icon: BookOpen, color: '#3d5cff' },
  { id: 'flashcards', label: 'Flashcards', icon: Layers, color: '#10c97b' },
  { id: 'mcq', label: 'MCQs', icon: HelpCircle, color: '#f59e0b' },
  { id: 'quiz', label: 'Quiz', icon: Trophy, color: '#f43f5e' },
]

export function ResultsPanel({ data, onReset }) {
  const [activeTab, setActiveTab] = useState('notes')

  // Build full download text
  const buildDownloadText = () => {
    const { subject, summary, notes, flashcards, mcqs, quiz } = data
    const lines = [
      `========================================`,
      `  STUDY MATERIALS: ${subject?.toUpperCase()}`,
      `  Generated by StudyAI`,
      `========================================`,
      '',
      `SUMMARY`,
      `-------`,
      summary || '',
      '',
      `KEY POINTS`,
      `----------`,
      ...(notes.keyPoints || []).map((p, i) => `${i + 1}. ${p}`),
      '',
      `STUDY NOTES`,
      `-----------`,
      ...(notes.sections || []).flatMap((s) => [`## ${s.heading}`, s.content, '']),
      '',
      `FLASHCARDS`,
      `----------`,
      ...(flashcards || []).flatMap((c, i) => [`Q${i + 1}: ${c.front}`, `A${i + 1}: ${c.back}`, '']),
      '',
      `MULTIPLE CHOICE QUESTIONS`,
      `-------------------------`,
      ...(mcqs || []).flatMap((q, i) => [
        `Q${i + 1}: ${q.question}`,
        ...(q.options || []).map((o, j) => `  ${String.fromCharCode(65 + j)}. ${o}`),
        `Answer: ${String.fromCharCode(65 + q.correctIndex)}`,
        q.explanation ? `Explanation: ${q.explanation}` : '',
        '',
      ]),
      '',
      `QUIZ`,
      `----`,
      ...(quiz || []).flatMap((q, i) => [
        `Q${i + 1} [${(q.difficulty || 'medium').toUpperCase()}]: ${q.question}`,
        ...(q.options || []).map((o, j) => `  ${String.fromCharCode(65 + j)}. ${o}`),
        `Answer: ${String.fromCharCode(65 + q.correctIndex)}`,
        q.explanation ? `Explanation: ${q.explanation}` : '',
        '',
      ]),
    ]
    return lines.join('\n')
  }

  const handleDownload = () => {
    const text = buildDownloadText()
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `study-notes-${(data.subject || 'notes').toLowerCase().replace(/\s+/g, '-')}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="animate-slide-up">
      {/* Summary bar */}
      <div
        className="card p-5 mb-6"
        style={{ background: 'linear-gradient(135deg, rgba(61,92,255,0.06), rgba(16,201,123,0.06))' }}
      >
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h2 className="font-bold text-lg" style={{ fontFamily: 'var(--font-display)' }}>
              ✨ {data.subject || 'Study Materials Generated!'}
            </h2>
            {data.summary && (
              <p className="text-sm mt-1" style={{ color: 'var(--text-secondary)', maxWidth: '500px' }}>
                {data.summary}
              </p>
            )}
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            <button
              onClick={handleDownload}
              className="copy-btn flex items-center gap-2"
            >
              <Download size={13} />
              Download All
            </button>
            <button
              onClick={onReset}
              className="copy-btn flex items-center gap-2"
            >
              <RefreshCw size={13} />
              New PDF
            </button>
          </div>
        </div>
      </div>

      {/* Tab navigation */}
      <div
        className="flex gap-1 p-1 rounded-xl mb-6 overflow-x-auto"
        style={{ background: 'var(--bg-secondary)' }}
        role="tablist"
      >
        {tabs.map(({ id, label, icon: Icon, color }) => (
          <button
            key={id}
            role="tab"
            aria-selected={activeTab === id}
            onClick={() => setActiveTab(id)}
            className="flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-semibold transition-all flex-shrink-0"
            style={{
              fontFamily: 'var(--font-display)',
              background: activeTab === id ? 'var(--bg-card)' : 'transparent',
              color: activeTab === id ? color : 'var(--text-muted)',
              boxShadow: activeTab === id ? '0 2px 8px rgba(0,0,0,0.08)' : 'none',
            }}
          >
            <Icon size={15} />
            {label}
          </button>
        ))}
      </div>

      {/* Tab content */}
      <div>
        {activeTab === 'notes' && (
          <>
            <NotesSection notes={data.notes} subject={data.subject} />
            <InContentAd id="after-notes" />
          </>
        )}

        {activeTab === 'flashcards' && (
          <>
            <FlashcardsSection flashcards={data.flashcards} />
            <InContentAd id="after-flashcards" />
          </>
        )}

        {activeTab === 'mcq' && (
          <>
            <MCQSection mcqs={data.mcqs} />
            <InContentAd id="before-quiz" />
          </>
        )}

        {activeTab === 'quiz' && (
          <QuizSection quiz={data.quiz} />
        )}
      </div>

      {/* Generate another CTA */}
      <div className="text-center mt-12 py-10" style={{ borderTop: '1px solid var(--border)' }}>
        <p
          className="font-bold text-xl mb-3"
          style={{ fontFamily: 'var(--font-display)' }}
        >
          Have another PDF to study?
        </p>
        <p className="text-sm mb-6" style={{ color: 'var(--text-secondary)' }}>
          Generate study materials for as many PDFs as you need — completely free.
        </p>
        <button
          onClick={onReset}
          className="btn-primary flex items-center gap-2 mx-auto"
        >
          <RefreshCw size={16} />
          Generate Another PDF
        </button>
      </div>
    </div>
  )
}
